### ISSUE TITLE
Deploying to production

### ISSUE THREAD

**Issue by BlondeBubblyBryan** [AmirAhrari/django-react-ecommerce#8]
Hi there! Amazing work you have here! Would it be possible if you added instructions on how you would deploy this project using docker in the README.md? Thank you so much!

**Comment by AmirAhrari** [comment]
Hi thank you! I added deployment [guide](https://github.com/AmirAhrari/django-react-ecommerce/commit/2daa7e5c9c8476d10182a12af35a60223b42237f) using docker :)
